# Estágio 1: Build do Frontend React com Vite
FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

# Estágio 2: Servidor Nginx para os arquivos estáticos e proxy
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY devops/config/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
