apiVersion: v1
kind: ConfigMap
metadata:
  name: curriculo-config
  namespace: curriculo-online
data:
  APP_ENV: "production"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "curriculo_online"
  STORAGE_MODE: "auto"
  DEFAULT_LANG: "pt"
---
apiVersion: v1
kind: Secret
metadata:
  name: curriculo-secrets
  namespace: curriculo-online
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASS: "root_secure_k8s"
